version: '3.8'

services:
  vector-translation-gpu:
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
    container_name: vector-translation-gpu
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - CUDA_VISIBLE_DEVICES=0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - ./models:/app/models:ro  # Mount model cache
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    
  # Fallback CPU version
  vector-translation-cpu:
    build:
      context: .
      dockerfile: Dockerfile
      target: cpu-base
    container_name: vector-translation-cpu
    ports:
      - "5001:5000"
    environment:
      - PORT=5000
    profiles:
      - cpu-fallback
    volumes:
      - ./models:/app/models:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

networks:
  default:
    name: vector-translation-network 